USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/Coolpad/8297/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6592
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := 8297

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/Coolpad/8297/kernel

BOARD_HAS_NO_SELECT_BUTTON := true

#Make Recovery
TOOLS_DIR := device/Coolpad/8297/tools
RECOVERY_ROOT_DIR := out/target/product/8297/recovery/root
BOARD_CUSTOM_BOOTIMG_MK := device/Coolpad/8297/mkbootimg.mk

#Cwm Recovery
BOARD_USE_CUSTOM_RECOVERY_FONT := \"fontcn30_18x48.h\"
BOARD_RECOVERY_MTK := true
